"""
SynJuris v2.3 — Forensic Proof Generator
=========================================
Generates a human-readable "Chain of Custody" statement for a specific exhibit.
"""

import sqlite3
import datetime
import sys
from merkle_dag import MerkleDAG

def generate_exhibit_affidavit(case_id, exhibit_id, db_path="synjuris.db"):
    """
    Generates a formal forensic statement for a piece of evidence.
    """
    try:
        dag = MerkleDAG(case_id, db_path)
        
        conn = sqlite3.connect(db_path)
        c = conn.cursor()
        # Fetch evidence details
        c.execute("SELECT title, content, category, trace_hash, created_at FROM evidence WHERE id=?", (exhibit_id,))
        exhibit = c.fetchone()
        conn.close()
        
        if not exhibit:
            return f"Error: Exhibit ID {exhibit_id} not found in database."

        title, content, category, trace_hash, timestamp = exhibit
        root_hash = dag.get_root_hash()
        
        affidavit = f"""
==================================================
        DIGITAL CHAIN OF CUSTODY AFFIDAVIT
==================================================
CASE REFERENCE : {case_id}
EXHIBIT ID     : {exhibit_id}
DOCUMENT TITLE : {title}
CATEGORY       : {category}
CAPTURE DATE   : {timestamp}

[CRYPTOGRAPHIC PROOF]
SOURCE HASH (SHA-256):
{trace_hash}

[MERKLE DAG VERIFICATION]
CURRENT DAG ROOT HASH:
{root_hash}

VERIFICATION STATUS: 
[✓] SECURELY ANCHORED IN LOCAL AUDIT LEDGER

JURISDICTIONAL STATEMENT:
This digital exhibit has been hashed and entered into the 
SynJuris Merkle Directed Acyclic Graph (DAG). Any 
unauthorized modification to the source document will 
break the cryptographic chain, rendering the hash invalid.

This process ensures the TEMPORAL INTEGRITY and 
CONTENT IMMUTABILITY of the evidence for legal proceedings.
==================================================
Generated by SynJuris v2.3 | {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
        return affidavit
    except Exception as e:
        return f"System Error: {str(e)}"

if __name__ == "__main__":
    # Check for Command Line Arguments: python proof_generator.py <case_id> <exhibit_id>
    if len(sys.argv) > 2:
        try:
            cid = int(sys.argv[1])  # fixed: was sys.argv
            eid = int(sys.argv[2])  # fixed: was sys.argv
            print(generate_exhibit_affidavit(cid, eid))
        except ValueError:
            print("Usage: python proof_generator.py [case_id] [exhibit_id]")
    else:
        # Default fallback for testing
        print("--- RUNNING DEFAULT TEST (CASE 1, EXHIBIT 1) ---")
        print(generate_exhibit_affidavit(1, 1))
        print("\nTIP: Run 'python proof_generator.py <case_id> <exhibit_id>' for specific files.")
